//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_15_11_2022_cvety
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order = new HashSet<Order>();
        }
    
        public string ProductArticleNumber { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string ProductCategory { get; set; }
        public byte[] ProductPhoto { get; set; }
        public string ProductManufacturer { get; set; }
        public Nullable<decimal> ProductCost { get; set; }
        public Nullable<int> ProductDiscountAmount { get; set; }
        public Nullable<int> ProductQuantityInStock { get; set; }
        public string ProductStatus { get; set; }
        public string ImgPath
        {
            get
            {
                return "/Resources/" + this.ProductArticleNumber + ".jpg";
            }
        }
        public string FullProductName
        {
            get
            {
                return "Наименование товара: " + this.ProductName;
            }
        }
        public string FullProductDescription
        {
            get
            {
                return "Описание товара: " + this.ProductDescription;
            }
        }
        public string FullProductManufacturer
        {
            get
            {
                return "Производитель: " + this.ProductManufacturer;
            }
        }
        public string FullProductCost
        {
            get
            {
                return "Цена: " + this.ProductCost;
            }
        }
        public string FullProductQuantityInStock
        {
            get
            {
                return "На складе: " + this.ProductQuantityInStock;
            }
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
